# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('addr', models.CharField(max_length=100, null=True)),
                ('office', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='UNNAMED', max_length=50, verbose_name='matter name')),
                ('region', models.CharField(blank=True, max_length=20)),
                ('billing_group', models.CharField(blank=True, max_length=30, verbose_name='Billing group')),
                ('office', models.CharField(blank=True, max_length=20, verbose_name='matter management office')),
                ('service_area', models.CharField(blank=True, max_length=30, verbose_name='Service Area')),
                ('partner', models.CharField(blank=True, max_length=30, verbose_name='matter management partner')),
                ('desc', models.TextField(blank=True, verbose_name='matter description')),
                ('billable_hrs', models.FloatField(default=0, verbose_name='billable hours')),
                ('fees_billed', models.FloatField(default=0, verbose_name='fees billed')),
                ('avg_bill_rate', models.FloatField(default=0, verbose_name='average bill rate')),
                ('profitability', models.FloatField(default=0)),
            ],
            options={
                'ordering': ('date_created',),
            },
        ),
    ]
